### ISSUE TITLE
Difficulties with Quickstart Documentation

### ISSUE THREAD

**Issue by troyfontaine** [lyft/omnibot#23]
I'm attempting to follow the quickstart documentation and have encountered some difficulties.  I'd be happy to contribute with some documentation updates-I just need to get my configuration working so I can be sure that I'm on the right track.

- Is there an example logging.yaml file available?  I'm not seeing very much log output while trying to troubleshoot from watcher and webhook.
- The webhook doesn't appear to enter a monitoring loop as it is explained in the docs-but I am seeing the events passed through to omnibot
- I see there is a PR for a number of fixes, possibly related to the deprecation of the legacy tokens?  Legacy tokens are no longer available as of Tuesday May 5th, 2020
- When using the bot_token and user_token for an app, you're no longer able to access emoji.list (I'm not seeing this error when using the branch `api-fixes-and-logging-improvements`
- The bot does not appear able to reply to messages after being added to a channel (this is my primary problem currently)
- watcher only emits the logging.yaml warning and then this `UNLOCK_SCRIPT not cached.`

My handlers for testing are:
```yaml
  message_handlers:
    - match: ".*(@here|@channel).*"
      match_type: "regex"
      description: "Warn on @here or @channel."
      bots:
        "my_slack":
          - "devbot"
      callbacks:
        - module: "omnibot.callbacks.message_callbacks:specials_callback"
          kwargs:
            channels:
              random:
                message: "Please don't `{special}` as it notifies {member_count} people."
                reaction: "broken_heart"
    - match: "Got milk*"
      match_type: "regex"
      description: "Got milk?"
      bots:
        "my_slack":
          - "devbot"
      callbacks:
        - module: "omnibot.callbacks.message_callbacks:specials_callback"
          kwargs:
            channels:
              random:
                message: "I LOVE MILK!!!"
                reaction: "heart"
    - match: ""
      match_type: "command"
      match_mention: True
      description: "testing"
      canned_response: "PROCESSING..."
      bots:
        "my_slack":
          - "devbot"
      callbacks:
        - module: "omnibot.callbacks.message_callbacks:test_callback"
          kwargs:
            text: 'test'
```

Thanks!
